apply plugin: 'com.android.application'

android {
    namespace 'com.meir.minyanimkrovim'
    compileSdk 34

    defaultConfig {
        applicationId "com.meir.minyanimkrovim"
        minSdk 19
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            outputFileName = "minyanim-krovim-${variant.versionName}-${variant.name}.apk"
        }
    }
}
